"""empty message

Revision ID: 42516dbf9c68
Revises: edc13e04887e
Create Date: 2021-07-29 11:34:55.843158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42516dbf9c68'
down_revision = 'edc13e04887e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('console_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('loose_price', sa.String(length=255), nullable=True),
    sa.Column('cib_price', sa.String(length=255), nullable=True),
    sa.Column('new_price', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('release_date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'release_date')
    op.drop_table('games_data')
    # ### end Alembic commands ###
