"""empty message

Revision ID: 6de093906547
Revises: 42516dbf9c68
Create Date: 2021-08-04 16:18:07.318802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de093906547'
down_revision = '42516dbf9c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'review',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'review',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
