"""empty message

Revision ID: 52041cd5a523
Revises: 6de093906547
Create Date: 2021-08-05 14:03:21.802617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52041cd5a523'
down_revision = '6de093906547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'collection_img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('consoles', 'console_img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consoles', 'console_img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('collections', 'collection_img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
